export const TWENTY_FOUR_HOURS_IN_MILLISECONDS = 24 * 60 * 60 * 1000;

export const SOLAR_TRACKER_CRON_INTERVAL = 15; // minutes
export const SOLAR_TRACKER_CRON_PATTERN = `0 */${SOLAR_TRACKER_CRON_INTERVAL} * * * *`;	
export const SOLAR_TRACKER_CRON_INTERVAL_IN_MILLISECONDS = SOLAR_TRACKER_CRON_INTERVAL * 60 * 1000;

export const WEATHER_STATION_CRON_INTERVAL = 10; // minutes
export const WEATHER_STATION_CRON_PATTERN = `0 */${WEATHER_STATION_CRON_INTERVAL} * * * *`;
export const WEATHER_STATION_CRON_INTERVAL_IN_MILLISECONDS = WEATHER_STATION_CRON_INTERVAL * 60 * 1000;